-- TABLE => ENTITY
-- ROW => TUPLE
-- COLUMN => ATTRIBUTE

-- DDL => CREATE, ALTER, DROP, TRUNCATE
-- DML => INSERT, UPDATE, DELETE
-- DRL  => SELECT
-- DCL => GRANT, REVOKE
-- TCL => COMMIT, ROLLBACK, SAVEPOINT





CREATE TABLE STUDENT (
    STUID NUMBER(4),
    STNAME VARCHAR(10),
    CLASS NUMBER(4) DEFAULT 1,
    REG_DATE DATE DEFAULT SYSDATE
);

SELECT
    *
FROM
    STUDENT;

DESC STUDENT;

ALTER TABLE STUDENT ADD COURSE VARCHAR2(10);

ALTER TABLE STUDENT MODIFY COURSE VARCHAR2(20);

ALTER TABLE STUDENT DROP COLUMN REG_DATE;

INSERT INTO STUDENT VALUES (
    1234,
    'beena',
    2,
    'SCIENCE'
);

ALTER TABLE STUDENT DROP COLUMN COURSE;

ALTER TABLE STUDENT ADD REG_DATE DATE DEFAULT SYSDATE;

INSERT INTO STUDENT (
    STUID,
    STNAME
) VALUES (
    2345,
    'vikram'
);

SELECT
    STNAME ||'-'|| CLASS
FROM
    STUDENT;

CREATE TABLE DEPT (
    DEPTID CHAR(3) PRIMARY KEY,
    NAME CHAR(50) NOT NULL
);

SELECT
    *
FROM
    DEPT;

DESC DEPT;

INSERT INTO DEPT VALUES (
    'MOB',
    'Maurya'
);

INSERT INTO DEPT VALUES (
    'BD',
    'Tiwari'
);

INSERT INTO DEPT VALUES (
    'MS',
    'Sharma'
);

INSERT INTO DEPT VALUES (
    'HRS',
    'Lee'
);

CREATE TABLE EMPLOYEE (
    ID INT PRIMARY KEY,
    NAME CHAR(50) NOT NULL,
    DEPTID CHAR(3),
    FOREIGN KEY(DEPTID) REFERENCES DEPT(DEPTID) ON DELETE CASCADE,
    CONSTRAINT CHK_ID CHECK (ID BETWEEN 1 AND 50000)
);

DESC EMPLOYEE;

INSERT INTO EMPLOYEE VALUES(
    2,
    'Maurya',
    'MOB'
);

SELECT
    *
FROM
    EMPLOYEE;

ALTER TABLE EMPLOYEE RENAME COLUMN DEPTID TO DEPT;

SELECT
    *
FROM
    STUDENT;

SELECT
    STNAME
FROM
    STUDENT
WHERE
    CLASS IN (2,
    3);

-- CREATE TABLE STUDENT (
--     STUID NUMBER,
--     FIRSTNAME VARCHAR(5),
--     LASTNAME VARCHAR(5),
--     SCORE NUMBER(3)
-- );

CREATE TABLE METER (
    ID INT PRIMARY KEY,
    BUILDING_ID INT NOT NULL,
    METER_NUMBER VARCHAR2(100)
);

DROP TABLE METER;

CREATE TABLE BUILDING (
    ID INT PRIMARY KEY,
    OWNER_NAME VARCHAR2(100),
    ADDRESS VARCHAR2(100),
    BUILDING_TYPE_ID INT,
    FOREIGN KEY(BUILDING_TYPE_ID) REFERENCES METER(BUILDING_ID),
    CONTACT_NUMBER VARCHAR2(100),
    EMAIL_ADDRESS VARCHAR2(100)
);

SELECT
    *
FROM
    METER;

DESC METER;
